version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - start-dockerd
  build:
    commands:
      - python /deploy_logic/deploy_image.py --new_images new_images.yml
