"""Configuration to define driver and executor memory."""

DRIVER_MEM_INSTANCE_MEM_RATIO = 0.9
DRIVER_MEM_OVERHEAD_RATIO = 0.1
EXECUTOR_MEM_INSTANCE_MEM_RATIO = 0.95
EXECUTOR_MEM_OVERHEAD_RATIO = 0.1
EXECUTOR_CORES = 5
HADOOP_DAEMONS_MEM_MB = 1024
SAFE_MEMORY_REDUCTION_RATIO = 0.95
EXECUTOR_MEM_INSTANCE_MEM_RATIO_ADV = 0.90
AWS_SPARK_CONFIG_MODE_STANDARD = 1
AWS_SPARK_CONFIG_MODE_ADVANCED = 2
